cloudposse/terraform-aws-cloudfront-s3-cdn

- main.tf
* Change `tf_vanity` to `terraform-aws-reoute53-alias`
* Conforming to new TF registry conventions
> Update new `terraform-aws-route53-alias` module

- .gitignore
- .travis.yml
- LICENSE
- Makefile
- README.md
- main.tf
- variables.tf
* `terraform fmt`
* Added `TravisCI`
* Added conditional for `cloudfront_default_certificate`
* Updated `README`
* Terraform lint
* To monitor build status
* If `acm_certificate_arn` or `iam_certificate_id` is specified, `cloudfront_default_certificate` must be set to `false`, otherwise Terraform will try to recreate the certificate on each `plan/apply` 
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/8
* Added a note to `README` that to use an ACM Certificate with Amazon CloudFront, you must request or import the certificate only in the US East (N. Virginia) region
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/10
> Add TravisCI. Fix CloudFront default certificate

- main.tf
* Bumped module versions
* `terraform fmt` required for the old versions
> Bump module versions

- main.tf
- variables.tf
* Use `attributes` variable in child modules
* For consistency, we need to propagate all `attributes` downstream
> Fix attributes

- .gitignore
- README.md
- example/index.html
- example/main.tf
- example/outputs.tf
- example/provider.tf
- main.tf
- outputs.tf
- variables.tf
* Add support for Regional Endpoint
> Added optional regional s3 endpoint. Added Example

- README.md
- docs/terraform.md
- main.tf
- variables.tf
Make minimim_protocol_version configurable.
(I wasn't able to run `make readme` to completion as this repo and/or the included build harness fails due to presupposed binaries (`/bin/bash: gomplate: command not found`) whose origins are not documented)
> make minimim_protocol_version configurable

- README.md
- docs/targets.md
- docs/terraform.md
- example/main.tf
- main.tf
- variables.tf
* Add forwarded headers so that s3 bucket can identify origins.
* Its missing and causes an error
* https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/
> Forwarded headers are needed when using CORS on S3 from cloudfront

- main.tf
Changing the way bucket_name is populated in locals. Deriving the name from the s3 bucket resource attribute, instead of the s3 bucket argument.
S3 bucket attributes only exist after a resource has been made, currently S3 bucket resource arguments are used to populated a `local`.  This  change will make sure that the `local.bucket` falls back to `var.origin_bucket`. Without this change the datasource `aws_s3_bucket.selected` will try to use a bucket name which has not been created yet.
* closes #31
> Populate local.bucket with aws_s3_bucket resource attributes, not arguments.

- README.md
- docs/terraform.md
- main.tf
- variables.tf
Add lambda_function_association to variables.
```
module "cdn" {
source                   = "../"
namespace                = "eg"
stage                    = "prod"
name                     = "app"
aliases                  = ["assets.cloudposse.com"]
parent_zone_id           = "${aws_route53_zone.primary.zone_id}"
use_regional_s3_endpoint = "true"
origin_force_destroy     = "true"
cors_allowed_headers     = ["*"]
cors_allowed_methods     = ["GET", "HEAD", "PUT"]
cors_allowed_origins     = ["*.cloudposse.com"]
cors_expose_headers      = ["ETag"]
lambda_function_association = [
{
event_type = "viewer-request"
lambda_arn = "arn:aws:lambda:us-east-1:${var.account_id}:function:${local.func_name}:12"
},
]
}
```
When using attributes of your own resource, the following error will be occurred. …
> Add lambda_function_association

- README.md
- docs/terraform.md
- main.tf
- variables.tf
Add support for `wait_for_deployment` variable. It has been added to the 2.5.0 AWS terraform provider. 
https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#250-april-05-2019
> Add wait_for_deployment

- main.tf
`var.enabled` been changed to type `bool` but the `dns` module used within this module was still comparing it to a string.
This is causing the DNS record to be removed even when enabled is true and `var.parent_zone_id` is provided.
The `cloudposse/terraform-aws-route53-alias` module has also had it's `var.enabled` changed to type `bool`.
> var.enabled is a bool not a string

- README.md
- docs/terraform.md
- main.tf
- variables.tf
My org, and I would imagine others, prefers to encrypt s3 buckets even when not entirely necessary just for uniformity in our internal security audits.
This fixes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/54
> Added the option to add aes256 sse

- README.md
- README.yaml
I found a dead link in your readme and fixed it.
> Fix link to examples in README

- README.md
- docs/terraform.md
- main.tf
- variables.tf
This is related to cloudposse/terraform-aws-cloudfront-s3-cdn#64
> Added optional support for ipv6 dns records

- LICENSE
- README.md
- README.yaml
- docs/terraform.md
- examples/complete/fixtures.us-east-2.tfvars
- main.tf
- test/src/examples_complete_test.go
- variables.tf
* Fix IPv6 variables
* Change AWS region for tests
* Fix `enabled` logic
* Use `terraform-null-label` instead of `terraform-terraform-label`
* Update LICENSE
* Duplicate `ipv6_enabled` variables - we need only one flag
* We use `us-east-2` region for Terratest now (`us-west-1` is very limited region)
* `enabled ` logic for `module "dns"` was wrong
* `terraform-null-label` has more features and works without issues in TF 0.12
* Closes #64
> Fix IPv6 variables. Change AWS region for tests. Fix `enabled` logic. Update LICENSE

- main.tf
If we give alias but not give acm_certificate_arn. Will have following error:
> Error: error creating CloudFront Distribution: InvalidViewerCertificate: To add an alternate domain name (CNAME) to a CloudFront distribution, you must attach a trusted certificate that validates your authorization to use the domain name. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements
This PR empty alias for cloudfront distribution to avoid this error.
> Empty alias if no acm_certificate_arn given

- README.md
- docs/terraform.md
- main.tf
- variables.tf
For some reason https://github.com/cloudposse/terraform-aws-cloudfront-cdn is not supporting terraform 0.12 . So I switch to use this module. And to host entire website. Use S3 static website as origin is much better to serve entire website. There is an old issue #14. But it didn't use the website URL as the origin. 
The main benefit is. When we have following files in S3:
```
- index.html
- photo/index.html
```
And when user navigate to `/photo` (without ending `/`). The S3 origin will return 404. But the S3 Static Website will return 302 redirect to `/photo/`.
Which is documented in last part of: https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html
> However, if you exclude the trailing slash from the preceding URL, Amazon S3 first looks for an object photos in the …
> Add website mode to use S3 static website as origin

- main.tf
Fix the issue mentioned in #74 
The s3 static website's domain have [two format][f]:
Format 1:
http://bucket-name.s3-website.Region.amazonaws.com
Format 2:
http://bucket-name.s3-website-Region.amazonaws.com
Could be `.` or `-` to concat `s3-website` and region code. And the selection of format is based on region. There is a [mapping table][t] for this. And according to this table. I found only old regions use format 1. Other newer regions all use format 2
In this PR. I created a list of the old regions. And all other regions(including future regions) will use format 2.
[f]: https://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html#root-domain-walkthrough-test-website
[t]:https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
> S3 website domain name might use `-` or `.`  as concatenator

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/slash-command-dispatch.yml
* Add `slash-command-dispatch` GitHub Actions workflow
* In a repo with the GitHub actions workflow present, when a PR is opened, we can comment on the PR with commands `/build-readme` and `/terraform-fmt` to rebuild README and format terraform code and push the changes back to the PR repo
> Add `slash-command-dispatch` GitHub Actions workflow

- README.md
- docs/terraform.md
- main.tf
- variables.tf
These ordered caches have the same support, with the same api, as the
default cache already in this module.
This fixes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/62
> Added support for any number of ordered caches

- README.md
- docs/terraform.md
- main.tf
- variables.tf
When specifying var.origin_bucket, it can be nice to leave the existing bucket's policy as is.
As an example, I manage an s3 bucket that multiple CloudFront dists use as their origin (without paths, they just use the same code).
In this case, I do not want to restrict the bucket to only talk to a single CF dist, as this module does by default.
> Make it optional to override the origin s3 policy

- README.md
- docs/terraform.md
- main.tf
- variables.tf
Update to latest label module to support the environment attribute
* Add compatibility with the latest label module's version
* s3 bucket module has the same name in different environment
> Update bucket logging module version

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Allow reusing an existing cloudfront origin access identity
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-creating-oai-console
> If you already have an OAI, we recommend that you reuse it to simplify maintenance.
* So you don't have to create new cloudfront origin access identities
N/A
> Add existing cloudfront origin access identity

- main.tf
* Updated dependency modules to latest to support terraform 0.13.0
* Updated the dependency modules since they are not updated and facing error when using with Terraform 0.13.0
- logs -> 0.13.1
- dns -> 0.8.0
> Updated dependency module versions to latest

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* This change allows you to turn on versioning for objects in the bucket
* For building static websites, we require the use of s3+cdn that this module provides. However, in some instances, we would like to ability to roll back to a previous version. 
* Since this is meant for a "dev" like environment, we set the cdn ttl to very low to pull objects back from the s3 bucket.
* The reason we use the CDN is to support TLS since s3 does not.
* N/A
> Adding versioning to S3 origin bucket

- README.md
- docs/terraform.md
- main.tf
- versions.tf
set minimum versions for providers without pinning to a specific major version
the current method makes it very difficult to maintain or upgrade consistent provider versions within a project
https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions
> use minimum versions for provider pinning

- .github/CODEOWNERS
- README.md
- context.tf
- docs/terraform.md
- examples/complete/main.tf
- main.tf
- variables.tf
* Adds `var.dns_alias_enabled` variable for enforcing explicit opt-in to the CDN DNS Alias. 
* Upgrades to `context.tf` pattern
* The `dns_alias_enabled` flag is to get around an issue similar to https://github.com/cloudposse/terraform-aws-elasticsearch/pull/73. 
* `context.tf` upgrade to follow with the common Cloud Posse pattern. 
* Relevant thread on dns_alias_enabled in SweetOps: https://sweetops.slack.com/archives/CB6GHNLG0/p1600294860394500
> Adds explicit DNS alias _enabled flag + context.tf upgrade

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* This change allows you to configure the `origin_ssl_protocols` parameter
of the `aws_cloudfront_distribution` terraform resource. If this
parameter is not configured explicitly, the old default is kept.
* This is just for making the module more flexible.
* N/A
> make origin_ssl_protocols configurable

- README.md
- docs/terraform.md
- examples/complete/outputs.tf
- outputs.tf
This adds an output to access the Cloudfront distribution's Origin
Access identity, if it is enabled, else a blank string.
We need this to provide access to the Cloudfront distribution from an externally-written bucket policy.
Closes: #115
> Add cloudfront origin identity iam arn output

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* This change allows you to add a `aws_s3_bucket_public_access_block`
resource for the origin s3 bucket.
* On "Amazon S3 Preventative Security Best Practices" it is recommended
to use Amazon S3 block public access.
* https://docs.aws.amazon.com/AmazonS3/latest/dev/security-best-practices.html
> add option for aws_s3_bucket_public_access_block for origin

- README.md
- docs/terraform.md
- examples/complete/fixtures.us-east-2.tfvars
- examples/complete/main.tf
- examples/complete/variables.tf
- main.tf
- variables.tf
* `mfa_delete` removed
* Bridgecrew check `Ensure S3 bucket has MFA delete enabled` skipped
* Because terraform doesn't support this argument to be toggled (https://github.com/hashicorp/terraform-provider-aws/issues/629).
* To satisfy Bridgecrew compliance scan
* https://github.com/hashicorp/terraform-provider-aws/issues/629
> mfa_delete removed

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Disable versioning by-default for the logging bucket. This value is now user-configurable.
* In [terraform-aws-s3-log-storage 0.18.0](https://github.com/cloudposse/terraform-aws-s3-log-storage/releases/tag/0.18.0) versioning was added as a variable, but not added to the s3-cdn module.
* Versioning on the logging bucket does not make much sense, but can be turned on if desired.
* [terraform-aws-s3-log-storage 0.18.0](https://github.com/cloudposse/terraform-aws-s3-log-storage/releases/tag/0.18.0)
> feat: make logbucket versioning optional

- README.md
- docs/terraform.md
- main.tf
You can't modify an S3 bucket's policy & public access block at the same
time, AWS API will complain:
OperationAborted: A conflicting conditional operation is currently in progress against this resource
This error can appear during both deploy and destroy for the module.
Serialise operations to the origin bucket so we don't run into this
error. The suggested fix is from
https://github.com/hashicorp/terraform-provider-aws/issues/7628
> Serialise origin bucket modifications

- README.md
- docs/terraform.md
- main.tf
* Removed the old data.template_file source
* Use more recent providers so M1 can be used
* Closes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/139
> Replaced old data.template_file to use latest aws provider and tf

- main.tf
* Uses the bucket `website_endpoint` instead of the `bucket_regional_domain_name`
* The `bucket_regional_domain_name` is incorrectly documented in the hashicorp [aws_cloudfront_distribution](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution) docs
* Fixes an issue introduced in a recent PR which drops the `-website` portion of the domain
* Closes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/148
* Fixes previous PR https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/143/files#r604661084
@syphernl has confirmed that this fixes his issue by using the feature branch as a source.
> Use `website_endpoint` instead of `bucket_regional_domain_name`

- README.md
- README.yaml
* Use acm module instead of awscli
* Kept original awscli command for posterity
* Why use the CLI when you can use terraform ?
* Closes https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/26
> Use acm module instead of awscli

- README.md
- main.tf
* Fix creating a S3 bucket policy when using an existing S3 bucket.
* The code was only considering the bucket object managed by this module.
* Closes #152.
> Allow creating a policy for an existing S3 bucket

- main.tf
There is currently a bug introduced in version v0.64.0 which prevents CloudFront from connecting to the bucket. `bucket.website_domain = "s3-website-<region>.amazonaws.com"` (see AWS provider source code https://github.com/hashicorp/terraform-provider-aws/blob/ac06ced75cba0daf09fef2938752ad13cc6fff6e/aws/resource_aws_s3_bucket.go#L1747). In https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/blob/master/main.tf#L319 `local.bucket_domain_name` is used in CloudFront origin, but since it is  "s3-website.eu-central-1.amazonaws.com" (in our case) - CloudFront gets a redirect to https://aws.amazon.com/s3/ and nothing works...
> Use bucket.website_endpoint instead of bucket.website_domain

- README.md
- docs/terraform.md
- main.tf
- variables.tf
* Add the `allow_ssl_requests_only` flag to force the s3 bucket to only communicate over ssl
* AWS Foundational Security Best Practices
> add allow_ssl_requests_only to force ssl communication

- README.md
- README.yaml
* Fix use of `deployment_principal_arns` variable in README snippet.
* The IAM Role ARN supplied in the `deployment_principal_arns` map is actually using S3 ARNs. This fixes the ARNs such that they are IAM Role ARNs.
* N/A
> Fix README Snippet Use of `deployment_principal_arns`

- .github/auto-release.yml
- .github/workflows/auto-release.yml
- examples/complete/deployment.tf
- test/src/Makefile
- Update auto-release (release-drafter) GHA workflow to latest distribution from build-harness.
- Fix Terratest by ensuring IAM roles created by examples/complete are unique for each run (also increase test timeout).
- The latest distribution of the `auto-release` GHA workflow from https://github.com/cloudposse/build-harness allows merged PRs to be accumulated in a draft release when the `no-release` label is used. This allows PRs to be consolidated rather than each given their own release — as renovatebot will cause a rippling series of module updates across all repositories that use this module, and all repositories that use those modules, etc.
- This is a subset of `make github/init`, which will update all GHA-related files to the latest build-harness distribution. However, changing …
> Chore: Update `auto-release` (`release-drafter`) GHA workflow to latest distribution; fix Terratest

- README.md
- docs/terraform.md
- examples/complete/deployment.tf
- examples/complete/main.tf
- main.tf
* Do not hardcode AWS partition.
* Adds support for partitions other than `aws`, such as `aws-us-gov`.
* closes #200
> Fix: Do Not Hardcode AWS Partition

- README.md
- main.tf
* Sets the `viewer_certificate.ssl_support_method` to a non-empty value
* Since [AWS Provider 3.71.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.71.0) the `viewer_certificate.ssl_support_method` is being validated on plan-time and can no longer be an empty string but must be `sni-only` or `vip` (of which the latter incurs costs)
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#ssl_support_method
> fix: set viewer_certificate.ssl_support_method to a non-empty value

- README.md
- docs/terraform.md
- main.tf
- variables.tf
- versions.tf
- Add support for S3 object ownership controls.
- Misc: add BridgeCrew exceptions.
S3 object ownership controls should be configurable for the origin bucket behind the CloudFront distribution. If the origin bucket is used within CI pipelines, cross-account writes to the bucket will result in the object being owned by that account. This can result in 403's when attempting to access content in the CF distribution, unless the S3 object ownership setting is set to `BucketOwnerEnforced`.
> By default, when another AWS account uploads an object to your S3 bucket, that account (the object writer) owns the object, has access to it, and can grant other users access to it through ACLs.
The new S3 object ownership variable has as a default value that has the same effect if the new …
> Feat: Add Support for S3 Object Ownership Controls

- .github/auto-release.yml
- .github/renovate.json
- README.md
- docs/terraform.md
- versions.tf
- Allow AWS provider version `>= 4.9.0`
- Version 4.0.0 had breaking changes, so this module had pinned AWS provider `< 4.0`. Breaking changes were replaced with deprecation warnings in v4.9.0, so we can now allow later versions.
> Allow AWS provider version >= 4.9.0

- main.tf
* website enabled means we should use 
* Public Bucket
* No TLS Verify on bucket assets (not used by cloudfront in website mode)
* No Lambda Edge association
* Bugfix Website Mode
* 4. on [this doc](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/)
> bugfix `website_enabled`

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/auto-context.yml
- .github/workflows/auto-format.yml
- .github/workflows/auto-readme.yml
- .github/workflows/auto-release.yml
- .github/workflows/chatops.yml
- .github/workflows/validate-codeowners.yml
- README.md
- docs/terraform.md
- examples/complete/lambda-at-edge.tf
- examples/complete/lib/index.js
- examples/complete/versions.tf
- main.tf
- modules/lambda@edge/outputs.tf
- modules/lambda@edge/package.tf
- modules/lambda@edge/variables.tf
- modules/lambda@edge/versions.tf
- versions.tf
* Ability to specify source directory for Lambda@Edge submodule
* Currently, we can pass the list of files that will be archived and uploaded as Lambda sources. This is not an option if more advanced logic is used and a lot of files should be used.
**Example**
For example, we have the following file structure for lambda@edge submodule:
```
lambda_edge_example/
lib/
node_modules/
index.js
package.json
package-lock.json
context.tf
main.tf
outputs.tf
variables.tf
```
And we want the whole directory `lib` to be packaged.
With this enhancement path to `lib` might be specified like this
```terraform
module "lambda_edge" {
source  = "cloudposse/cloudfront-s3-cdn/aws//modules/lambda@edge"
version = "x.xx.x"
functions = {
viewer_request = {
source_dir   = "${path.module}/lib/"
runtime      = …
```
> Ability to specify source directory for Lambda@Edge submodule

- main.tf
disable creating acl resource in that case. 
BucketOwnerEnforeced s3 bucket can't have an acl.
* https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
> BucketOwnerEnforced s3 buckets can't have an acl

- examples/complete/website.tf
- main.tf
Restore `lookup()` calls in `main.tf` to address the `website_enabled = true` use case that was broken when #340 replaced them with explicit variable calls to avoid silent default value assignments. Additionally includes corresponding module instances in the test suite.
`website_enabled = true` implies a reference to 2 mutually exclusive configurations defined as the `local.website_config` variable. In the default case, `index_document`, `error_document`, and `routing_rules` elements exist, but `redirect_all_requests_to` does not, which leads to the following error:
```
╷
│ Error: Unsupported attribute
│
│   on ../../main.tf line 325, in resource "aws_s3_bucket" "origin":
│  325:       redirect_all_requests_to = website.value.redirect_all_requests_to
│     ├────────────────
│     │ …
```
> fix: Resolve unsupported attribute error in S3 website block
